10M_3_REF:
    172.168.1.10: 
        x_min: 0
        x_max: 2
        y_min: 0
        y_max: 2
        z_min: 0
        z_max: 10
        gt_distance: 9.2


    172.168.1.2: 
        x_min: 0
        x_max: 2
        y_min: 0
        y_max: 2
        z_min: 9
        z_max: 10
        gt_distance: 9.2